/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;
import java.sql.Connection;
import java.sql.SQLException;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import net.sf.jasperreports.engine.util.JRLoader;
import javax.swing.JFileChooser;
import java.io.File;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperFillManager;



/**
 *
 * @author Alumno
 */
public class Estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bntvergrafica = new javax.swing.JButton();
        btnverregistro = new javax.swing.JButton();
        btnexportarPDF = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1078, 721));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PezDiablo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(585, 1313));

        btnAtras.setBackground(new java.awt.Color(0, 102, 153));
        btnAtras.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras.png"))); // NOI18N
        btnAtras.setText("Atras ");
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setFocusPainted(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 102, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/encuesta (1).png"))); // NOI18N
        jLabel2.setText("ESTADISTICAS");

        bntvergrafica.setBackground(new java.awt.Color(0, 51, 102));
        bntvergrafica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/grafico-circular.png"))); // NOI18N
        bntvergrafica.setBorderPainted(false);
        bntvergrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntvergraficaActionPerformed(evt);
            }
        });

        btnverregistro.setBackground(new java.awt.Color(0, 51, 102));
        btnverregistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/A. Base de datos.png"))); // NOI18N
        btnverregistro.setBorderPainted(false);
        btnverregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverregistroActionPerformed(evt);
            }
        });

        btnexportarPDF.setBackground(new java.awt.Color(0, 51, 102));
        btnexportarPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/pdf (1).png"))); // NOI18N
        btnexportarPDF.setBorderPainted(false);
        btnexportarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexportarPDFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VER REGISTRO");

        jLabel4.setBackground(new java.awt.Color(204, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EXPORTAR PDF ");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("VER GRAFICA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnexportarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnverregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntvergrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(21, 21, 21)))
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnexportarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnverregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntvergrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
    Menu menu = new Menu(); 
    menu.setVisible(true);                
    this.dispose();  
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnverregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverregistroActionPerformed
        try {
        // Conexión directa a la base de datos
        Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/gestion_mar", "root", "12345678");

        // Ruta corregida al archivo .jrxml (ajústala si cambia)
        String ruta = "C:\\Users\\Alumno\\JaspersoftWorkspace\\MyReports/VerRegistro.jrxml";

        // Compilar el archivo .jrxml
        JasperReport reporte = JasperCompileManager.compileReport(ruta);

        // Enviar parámetros vacíos si no se usan
        Map<String, Object> parametros = new HashMap<>();

        // Llenar el reporte con la base de datos
        JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, parametros, conexion);

        // Mostrar el visor del reporte
        JasperViewer viewer = new JasperViewer(jasperPrint, false);
        viewer.setTitle("Reporte de especies registradas");
        viewer.setVisible(true);

        conexion.close();

    } catch (JRException e) {
        JOptionPane.showMessageDialog(null, "Error al generar el reporte: " + e.getMessage());
        e.printStackTrace();
    } catch (SQLException e){
        JOptionPane.showMessageDialog(null, "Error SQL: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnverregistroActionPerformed

    private void bntvergraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntvergraficaActionPerformed
    try {
        // Cargar driver JDBC
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Conexión
        Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/gestion_mar", "root", "12345678");

        // Ruta del jrxml
        String ruta = "C:/Users/Alumno/JaspersoftWorkspace/MyReports/VerGraficas.jrxml";

        // Compilar reporte
        JasperReport reporte = JasperCompileManager.compileReport(ruta);

        // Parámetros (vacío)
        Map<String, Object> parametros = new HashMap<>();

        // Llenar reporte
        JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, parametros, conexion);

        // Mostrar visor
        JasperViewer viewer = new JasperViewer(jasperPrint, false);
        viewer.setTitle("Gráfica de Especies");
        viewer.setVisible(true);

        conexion.close();

    } catch (ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(null, "Driver JDBC no encontrado: " + ex.getMessage());
    } catch (JRException ex) {
        JOptionPane.showMessageDialog(null, "Error JasperReports: " + ex.getMessage());
        ex.printStackTrace();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error SQL: " + ex.getMessage());
        ex.printStackTrace();
    }

    }//GEN-LAST:event_bntvergraficaActionPerformed

    private void btnexportarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexportarPDFActionPerformed
      try {
    // Conexión a la base de datos
    Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/gestion_mar", "root", "12345678");

    // Ruta al archivo JRXML
    String ruta = "C:\\Users\\Alumno\\JaspersoftWorkspace\\MyReports\\VerRegistro.jrxml";;

    // Compilar el reporte
    JasperReport reporte = JasperCompileManager.compileReport(ruta);

    // Parámetros (vacío si no usás)
    Map<String, Object> parametros = new HashMap<>();

    // Llenar el reporte
    JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, parametros, conexion);

    // Mostrar visor
    JasperViewer viewer = new JasperViewer(jasperPrint, false);
    viewer.setTitle("Reporte de especies registradas");
    viewer.setVisible(true);

    // Selector de archivo para guardar PDF
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Guardar reporte como PDF");
    fileChooser.setSelectedFile(new File("reporte_especies.pdf"));

    int seleccion = fileChooser.showSaveDialog(null);

    if (seleccion == JFileChooser.APPROVE_OPTION) {
        File archivoGuardar = fileChooser.getSelectedFile();

        // Exportar usando JasperExportManager (más simple)
        JasperExportManager.exportReportToPdfFile(jasperPrint, archivoGuardar.getAbsolutePath());

        JOptionPane.showMessageDialog(null, "PDF exportado correctamente:\n" + archivoGuardar.getAbsolutePath());
    }

    conexion.close();

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error en la base de datos: " + e.getMessage());
    e.printStackTrace();
} catch (JRException e) {
    JOptionPane.showMessageDialog(null, "Error en JasperReports: " + e.getMessage());
    e.printStackTrace();
}
    }//GEN-LAST:event_btnexportarPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntvergrafica;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnexportarPDF;
    private javax.swing.JButton btnverregistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
