/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.Locale;
import java.util.ResourceBundle;


public class Idiomas extends javax.swing.JFrame {


    /**
     * Creates new form Inicio
     */
    public Idiomas() {
        initComponents();
     cambiarIdioma("es", "ES");  
    }
   
    private void cambiarIdioma(String idioma, String pais) {
    Locale locale = new Locale(idioma, pais);
    ResourceBundle mensajes = ResourceBundle.getBundle("Languajes.Mensajes", locale, getClass().getClassLoader());

    tituloidiomas.setText(mensajes.getString("tituloidiomas"));
    subtituloinstrucciones.setText(mensajes.getString("subtituloinstrucciones"));

    btnespañol.setText(mensajes.getString("btnespañol"));
    btningles.setText(mensajes.getString("btningles"));
    btnfrances.setText(mensajes.getString("btnfrances"));
    btnportugues.setText(mensajes.getString("btnportugues"));
    btnarabe.setText(mensajes.getString("btnarabe"));
    btnrestableceridioma.setText(mensajes.getString("btnrestableceridioma"));
    btnAtras.setText(mensajes.getString("btnAtras"));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tituloidiomas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnrestableceridioma = new javax.swing.JButton();
        subtituloinstrucciones = new javax.swing.JLabel();
        btnespañol = new javax.swing.JButton();
        btningles = new javax.swing.JButton();
        btnfrances = new javax.swing.JButton();
        btnportugues = new javax.swing.JButton();
        btnarabe = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1078, 721));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/AA4.png"))); // NOI18N

        tituloidiomas.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        tituloidiomas.setForeground(new java.awt.Color(255, 255, 255));
        tituloidiomas.setText("IDIOMA DEL SISTEMA");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        btnrestableceridioma.setBackground(new java.awt.Color(0, 102, 204));
        btnrestableceridioma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnrestableceridioma.setForeground(new java.awt.Color(255, 255, 255));
        btnrestableceridioma.setText("Restablecer Idioma");
        btnrestableceridioma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnrestableceridioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestableceridiomaActionPerformed(evt);
            }
        });

        subtituloinstrucciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        subtituloinstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        subtituloinstrucciones.setText("SELECCIONE UN IDIOMA A APLICAR : ");

        btnespañol.setBackground(new java.awt.Color(0, 51, 102));
        btnespañol.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnespañol.setForeground(new java.awt.Color(255, 255, 255));
        btnespañol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banderas_Idiomas/espana.png"))); // NOI18N
        btnespañol.setText(" Español (España)");
        btnespañol.setBorderPainted(false);
        btnespañol.setContentAreaFilled(false);
        btnespañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnespañolActionPerformed(evt);
            }
        });

        btningles.setBackground(new java.awt.Color(0, 51, 102));
        btningles.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btningles.setForeground(new java.awt.Color(255, 255, 255));
        btningles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banderas_Idiomas/estados-unidos.png"))); // NOI18N
        btningles.setText(" Inglés  (Estados Unidos)");
        btningles.setBorderPainted(false);
        btningles.setContentAreaFilled(false);
        btningles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninglesActionPerformed(evt);
            }
        });

        btnfrances.setBackground(new java.awt.Color(0, 51, 102));
        btnfrances.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnfrances.setForeground(new java.awt.Color(255, 255, 255));
        btnfrances.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banderas_Idiomas/francia.png"))); // NOI18N
        btnfrances.setText(" Francés ");
        btnfrances.setBorderPainted(false);
        btnfrances.setContentAreaFilled(false);
        btnfrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfrancesActionPerformed(evt);
            }
        });

        btnportugues.setBackground(new java.awt.Color(0, 51, 102));
        btnportugues.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnportugues.setForeground(new java.awt.Color(255, 255, 255));
        btnportugues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banderas_Idiomas/brasil.png"))); // NOI18N
        btnportugues.setText(" Portugués (Brasil)");
        btnportugues.setBorderPainted(false);
        btnportugues.setContentAreaFilled(false);
        btnportugues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnportuguesActionPerformed(evt);
            }
        });

        btnarabe.setBackground(new java.awt.Color(0, 51, 102));
        btnarabe.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnarabe.setForeground(new java.awt.Color(255, 255, 255));
        btnarabe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Banderas_Idiomas/egipto.png"))); // NOI18N
        btnarabe.setText(" Árabe ");
        btnarabe.setBorderPainted(false);
        btnarabe.setContentAreaFilled(false);
        btnarabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarabeActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(0, 102, 153));
        btnAtras.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras.png"))); // NOI18N
        btnAtras.setText("Atras ");
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setFocusPainted(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subtituloinstrucciones)
                                    .addComponent(btnespañol)
                                    .addComponent(btningles)
                                    .addComponent(btnfrances)
                                    .addComponent(btnportugues)
                                    .addComponent(btnarabe))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tituloidiomas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnrestableceridioma, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloidiomas)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(subtituloinstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnespañol)
                .addGap(36, 36, 36)
                .addComponent(btningles)
                .addGap(35, 35, 35)
                .addComponent(btnfrances)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnportugues)
                .addGap(26, 26, 26)
                .addComponent(btnarabe)
                .addGap(17, 17, 17)
                .addComponent(btnrestableceridioma, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrestableceridiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestableceridiomaActionPerformed
       cambiarIdioma("es", "ES");

    }//GEN-LAST:event_btnrestableceridiomaActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Configuracion confi = new Configuracion();
        confi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnespañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnespañolActionPerformed
        cambiarIdioma("es", "ES");

    }//GEN-LAST:event_btnespañolActionPerformed

    private void btninglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninglesActionPerformed
        cambiarIdioma("en", "US");

    }//GEN-LAST:event_btninglesActionPerformed

    private void btnfrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfrancesActionPerformed
        cambiarIdioma("fr", "FR");

    }//GEN-LAST:event_btnfrancesActionPerformed

    private void btnportuguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnportuguesActionPerformed
        cambiarIdioma("pt", "BR");
    }//GEN-LAST:event_btnportuguesActionPerformed

    private void btnarabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarabeActionPerformed
        cambiarIdioma("ar", "EG");
    }//GEN-LAST:event_btnarabeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Idiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Idiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Idiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Idiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Idiomas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnarabe;
    private javax.swing.JButton btnespañol;
    private javax.swing.JButton btnfrances;
    private javax.swing.JButton btningles;
    private javax.swing.JButton btnportugues;
    private javax.swing.JButton btnrestableceridioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel subtituloinstrucciones;
    private javax.swing.JLabel tituloidiomas;
    // End of variables declaration//GEN-END:variables
}
