/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Alumno
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        lblcodigo = new javax.swing.JLabel();
        txtnombre_cientifico = new javax.swing.JTextField();
        lblnombre_comun = new javax.swing.JLabel();
        lblhabitat = new javax.swing.JLabel();
        txtnombre_comun = new javax.swing.JTextField();
        txthabitat = new javax.swing.JTextField();
        lblpoblacion_estimada = new javax.swing.JLabel();
        txtestado_conservacion = new javax.swing.JTextField();
        lblestado_conservacion = new javax.swing.JLabel();
        txtpoblacion_estimada = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        lblnombre_cientifico = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        lblcategoria = new javax.swing.JLabel();
        txtcategoria = new javax.swing.JTextField();
        btnlimpiar = new javax.swing.JButton();
        btntablaregistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1078, 721));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Peces.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(585, 1313));

        btnAtras.setBackground(new java.awt.Color(0, 102, 153));
        btnAtras.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras.png"))); // NOI18N
        btnAtras.setText("Atras ");
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setFocusPainted(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 102, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bloc.png"))); // NOI18N
        jLabel2.setText("REGISTRO");

        btnbuscar.setBackground(new java.awt.Color(0, 51, 102));
        btnbuscar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa.png"))); // NOI18N
        btnbuscar.setBorder(null);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        txtbuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 3));
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        btnactualizar.setBackground(new java.awt.Color(0, 51, 102));
        btnactualizar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnactualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/actualizar.png"))); // NOI18N
        btnactualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnactualizar.setBorderPainted(false);
        btnactualizar.setFocusable(false);
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        lblcodigo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblcodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblcodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escaneo-de-codigo-de-barras.png"))); // NOI18N
        lblcodigo.setText("Codigo :");

        txtnombre_cientifico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 3));
        txtnombre_cientifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre_cientificoActionPerformed(evt);
            }
        });

        lblnombre_comun.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblnombre_comun.setForeground(new java.awt.Color(255, 255, 255));
        lblnombre_comun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/pez-payaso.png"))); // NOI18N
        lblnombre_comun.setText("Nombre Comun :");

        lblhabitat.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblhabitat.setForeground(new java.awt.Color(255, 255, 255));
        lblhabitat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/estanque.png"))); // NOI18N
        lblhabitat.setText("Habitat :");

        txtnombre_comun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 3));
        txtnombre_comun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre_comunActionPerformed(evt);
            }
        });

        txthabitat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 3));
        txthabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthabitatActionPerformed(evt);
            }
        });

        lblpoblacion_estimada.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblpoblacion_estimada.setForeground(new java.awt.Color(255, 255, 255));
        lblpoblacion_estimada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/pez.png"))); // NOI18N
        lblpoblacion_estimada.setText("Poblacion Estimada : ");

        txtestado_conservacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 3));
        txtestado_conservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestado_conservacionActionPerformed(evt);
            }
        });

        lblestado_conservacion.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblestado_conservacion.setForeground(new java.awt.Color(255, 255, 255));
        lblestado_conservacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/conservacion-del-agua.png"))); // NOI18N
        lblestado_conservacion.setText("Estado Conservacion : ");

        txtpoblacion_estimada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 3));
        txtpoblacion_estimada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpoblacion_estimadaActionPerformed(evt);
            }
        });

        btnagregar.setBackground(new java.awt.Color(0, 51, 102));
        btnagregar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cheque.png"))); // NOI18N
        btnagregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnagregar.setBorderPainted(false);
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(0, 51, 102));
        btneliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/eliminar (1).png"))); // NOI18N
        btneliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btneliminar.setBorderPainted(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        lblnombre_cientifico.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblnombre_cientifico.setForeground(new java.awt.Color(255, 255, 255));
        lblnombre_cientifico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/investigacion.png"))); // NOI18N
        lblnombre_cientifico.setText("Nombre Cientifico : ");

        txtcodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 3));
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        lblcategoria.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblcategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblcategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cangrejo-de-rio.png"))); // NOI18N
        lblcategoria.setText("Categoria : ");

        txtcategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 3));
        txtcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcategoriaActionPerformed(evt);
            }
        });

        btnlimpiar.setBackground(new java.awt.Color(0, 51, 102));
        btnlimpiar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escoba.png"))); // NOI18N
        btnlimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimpiar.setBorderPainted(false);
        btnlimpiar.setFocusable(false);
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        btntablaregistro.setBackground(new java.awt.Color(0, 51, 102));
        btntablaregistro.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btntablaregistro.setForeground(new java.awt.Color(255, 255, 255));
        btntablaregistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/frequency.png"))); // NOI18N
        btntablaregistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btntablaregistro.setBorderPainted(false);
        btntablaregistro.setFocusable(false);
        btntablaregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntablaregistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblcategoria)
                                                    .addComponent(lblcodigo)
                                                    .addComponent(lblnombre_cientifico)
                                                    .addComponent(lblnombre_comun)
                                                    .addComponent(lblhabitat))
                                                .addGap(23, 23, 23)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txthabitat)
                                                    .addComponent(txtnombre_comun)
                                                    .addComponent(txtnombre_cientifico)
                                                    .addComponent(txtcategoria)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(29, 29, 29)
                                                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(12, 12, 12)
                                                        .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btntablaregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblpoblacion_estimada)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtpoblacion_estimada, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(11, 11, 11)))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(lblestado_conservacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtestado_conservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btntablaregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigo)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcategoria)
                    .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre_cientifico)
                    .addComponent(txtnombre_cientifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre_comun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre_comun))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhabitat)
                    .addComponent(txthabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpoblacion_estimada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpoblacion_estimada))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblestado_conservacion)
                    .addComponent(txtestado_conservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
    int codigo = Integer.parseInt(txtcodigo.getText().trim());
    String categoria = txtcategoria.getText().trim();
    String nombreCientifico = txtnombre_cientifico.getText().trim();
    String nombreComun = txtnombre_comun.getText().trim();
    String habitat = txthabitat.getText().trim();
    String poblacion = txtpoblacion_estimada.getText().trim().replace(",", "");
    String estadoConservacion = txtestado_conservacion.getText().trim();

    if (nombreCientifico.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Primero busque o indique el nombre científico a actualizar.");
        return;
    }

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/gestion_mar", "root", "12345678");

        String sql = "UPDATE especies_marinas SET codigo=?, categoria=?, nombre_comun=?, habitat=?, poblacion_estimada=?, estado_conservacion=? WHERE nombre_cientifico=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, codigo);
        ps.setString(2, categoria);
        ps.setString(3, nombreComun);
        ps.setString(4, habitat);
        ps.setString(5, poblacion);
        ps.setString(6, estadoConservacion);
        ps.setString(7, nombreCientifico);

        int resultado = ps.executeUpdate();

        if (resultado > 0) {
            JOptionPane.showMessageDialog(this, "Datos actualizados correctamente.");
            txtcodigo.setText("");
            txtcategoria.setText("");
            txtnombre_cientifico.setText("");
            txtnombre_comun.setText("");
            txthabitat.setText("");
            txtpoblacion_estimada.setText("");
            txtestado_conservacion.setText("");
            txtbuscar.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la especie para actualizar.");
        }

        ps.close();
        conn.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
    }

    }//GEN-LAST:event_btnactualizarActionPerformed

    private void txtnombre_cientificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre_cientificoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre_cientificoActionPerformed

    private void txtnombre_comunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre_comunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre_comunActionPerformed

    private void txthabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthabitatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthabitatActionPerformed

    private void txtestado_conservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestado_conservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestado_conservacionActionPerformed

    private void txtpoblacion_estimadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpoblacion_estimadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpoblacion_estimadaActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
    int codigo = Integer.parseInt(txtcodigo.getText().trim());
    String categoria = txtcategoria.getText().trim();
    String nombreCientifico = txtnombre_cientifico.getText().trim();
    String nombreComun = txtnombre_comun.getText().trim();
    String habitat = txthabitat.getText().trim();
    String poblacionEstimada = txtpoblacion_estimada.getText().trim();
    String estadoConservacion = txtestado_conservacion.getText().trim();
    

    // Validar que no estén vacíos
    if (nombreCientifico.isEmpty() || nombreComun.isEmpty() || habitat.isEmpty() || poblacionEstimada.isEmpty() || estadoConservacion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        return;
    }

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/gestion_mar", "root", "12345678");
        
        String sql = "INSERT INTO especies_marinas (codigo, categoria, nombre_cientifico, nombre_comun, habitat, poblacion_estimada, estado_conservacion) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, codigo);
        ps.setString(2, categoria);
        ps.setString(3, nombreCientifico);
        ps.setString(4, nombreComun);
        ps.setString(5, habitat);
        ps.setString(6, poblacionEstimada);
        ps.setString(7, estadoConservacion);

        int resultado = ps.executeUpdate();

        if (resultado > 0) {
            JOptionPane.showMessageDialog(this, "Especie agregada exitosamente.");
            // Limpiar campos si deseas
            txtcodigo.setText("");
            txtcategoria.setText("");
            txtnombre_cientifico.setText("");
            txtnombre_comun.setText("");
            txthabitat.setText("");
            txtpoblacion_estimada.setText("");
            txtestado_conservacion.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo agregar la especie.");
        }

        ps.close();
        conn.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
    }

    }//GEN-LAST:event_btnagregarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
    String codigotxt = txtbuscar.getText().trim();

    if (codigotxt.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese el código para buscar.");
        return;
    }

    int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar esta especie?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/gestion_mar", "root", "12345678");

            String sql = "DELETE FROM especies_marinas WHERE codigo=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, codigotxt);

            int resultado = ps.executeUpdate();

            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Especie eliminada exitosamente.");

                // Limpiar campos
                txtcodigo.setText("");
                txtcategoria.setText("");
                txtnombre_cientifico.setText("");
                txtnombre_comun.setText("");
                txthabitat.setText("");
                txtpoblacion_estimada.setText("");
                txtestado_conservacion.setText("");
                txtbuscar.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el codigo de especie para eliminar.");
            }

            ps.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
    Menu menu = new Menu(); 
    menu.setVisible(true);                
    this.dispose(); 
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String codigotxt = txtbuscar.getText().trim();

    if (codigotxt.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese el código para buscar.");
        return;
    }

    try {
        int codigo = Integer.parseInt(codigotxt); // Aquí ya no dará error

        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/gestion_mar", "root", "12345678");

        String sql = "SELECT * FROM especies_marinas WHERE codigo = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, codigo); // Usamos setInt porque codigo es entero

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            txtcodigo.setText(String.valueOf(rs.getInt("codigo")));
            txtcategoria.setText(rs.getString("categoria"));
            txtnombre_cientifico.setText(rs.getString("nombre_cientifico"));
            txtnombre_comun.setText(rs.getString("nombre_comun"));
            txthabitat.setText(rs.getString("habitat"));
            txtpoblacion_estimada.setText(rs.getString("poblacion_estimada"));
            txtestado_conservacion.setText(rs.getString("estado_conservacion"));
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró ningún registro con ese código.");
        }

        rs.close();
        ps.close();
        conn.close();

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El código debe ser un número válido.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
    }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoriaActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
       txtcodigo.setText("");
       txtcategoria.setText("");
       txtnombre_cientifico.setText("");
       txtnombre_comun.setText("");
       txthabitat.setText("");
       txtpoblacion_estimada.setText("");
       txtestado_conservacion.setText("");
       txtbuscar.setText("");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btntablaregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntablaregistroActionPerformed
    Tabla_Registros table = new Tabla_Registros(); 
    table.setVisible(true);                
    this.dispose();
    }//GEN-LAST:event_btntablaregistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btntablaregistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcategoria;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblestado_conservacion;
    private javax.swing.JLabel lblhabitat;
    private javax.swing.JLabel lblnombre_cientifico;
    private javax.swing.JLabel lblnombre_comun;
    private javax.swing.JLabel lblpoblacion_estimada;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcategoria;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtestado_conservacion;
    private javax.swing.JTextField txthabitat;
    private javax.swing.JTextField txtnombre_cientifico;
    private javax.swing.JTextField txtnombre_comun;
    private javax.swing.JTextField txtpoblacion_estimada;
    // End of variables declaration//GEN-END:variables
}
